"""empty message

Revision ID: 9331cbc8e2d0
Revises: 
Create Date: 2025-01-21 18:02:13.653699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9331cbc8e2d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('start_point', sa.String(length=100), nullable=False),
    sa.Column('end_point', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('estimated_delivery_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('customers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('shipments')
    op.drop_table('routes')
    # ### end Alembic commands ###
